AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda Container
Resources:


  Entrypoint:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: crawler-entrypoint
      Role: !GetAtt Role.Arn
      PackageType: Image
      Code:
        ImageUri: 275448561531.dkr.ecr.sa-east-1.amazonaws.com/crawler-entrypoint:latest
      Timeout: 10

  FeatureGeneration:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: crawler-feature-generation
      Role: !GetAtt Role.Arn
      PackageType: Image
      Code:
        ImageUri: 275448561531.dkr.ecr.sa-east-1.amazonaws.com/crawler-feature-generation:latest
      Timeout: 10
      Environment:
        Variables:
          TABLE_NAME: crawler_appearences

  Processing:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: crawler-processing
      Role: !GetAtt Role.Arn
      PackageType: Image
      Code:
        ImageUri: 275448561531.dkr.ecr.sa-east-1.amazonaws.com/crawler-processing:latest
      Timeout: 10
      Environment:
        Variables:
          QUEUE_URL: !Ref UrlsQueue
          TABLE_NAME: crawler_appearences
  
  BatchEvent:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: crawler-batch-event
      Role: !GetAtt Role.Arn
      PackageType: Image
      Code:
        ImageUri: 275448561531.dkr.ecr.sa-east-1.amazonaws.com/crawler-batch-event:latest
      Timeout: 10
      Environment:
        Variables:
          BUCKET: crawler-ml-challenge
          QUEUE_URL: !Ref UrlsQueue
          DEPTH: 5

  UrlsQueue:
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: urls-queue

  SQSTrigger:
    Type: AWS::Lambda::EventSourceMapping
    Properties: 
      EventSourceArn: !GetAtt UrlsQueue.Arn
      FunctionName: !Ref Processing

  Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: lambda-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: lambda-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 
                  - "cloudwatch:*"
                  - "ec2:DescribeSecurityGroups"
                  - "ec2:DescribeSubnets"
                  - "ec2:DescribeVpcs"
                  - "events:*"
                  - "iam:GetPolicy"
                  - "iam:GetPolicyVersion"
                  - "iam:GetRole"
                  - "iam:GetRolePolicy"
                  - "iam:ListAttachedRolePolicies"
                  - "iam:ListRolePolicies"
                  - "iam:ListRoles"
                  - "iam:PassRole"
                  - "kms:ListAliases"
                  - "lambda:*"
                  - "logs:*"
                  - "tag:GetResources"
                  - "s3:*"
                  - "sqs:*"
                  - "dynamodb:*"
                Resource: '*'
      MaxSessionDuration: 3600 